/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../../../../public/HouseModel.glb --transform 
Files: ../../../../../public/HouseModel.glb [62.14KB] > D:\Development\JavascriptProjects\SteenenburgDisplay\src\pages\Dashboard\pages\Map\HouseModel-transformed.glb [6.62KB] (89%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/HouseModel.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={12.308}>
        <mesh geometry={nodes.Plane_1.geometry} />
        <mesh geometry={nodes.Plane_2.geometry} />
        <mesh geometry={nodes.Plane_3.geometry} />
      </group>
    </group>
  );
}

useGLTF.preload("/HouseModel-transformed.glb");
